services:
  - type: web
    name: backend
    env: docker
    dockerContext: backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
